# Project information
site_name: Secrets
site_description: Secrets, credentials, and other cloak-and-dagger stuff
site_author: thfis
site_url: 'https://dfds.github.io/secrets/'
copyright: DFDS A/S

# Repository
repo_name: 'Secrets'
repo_url: 'https://github.com/dfds/secrets'

theme:
  name: material
  custom_dir: theme
  palette:
    primary: indigo
    accent: indigo
  logo:
    icon: security
  feature:
    tabs: true

markdown_extensions:
- admonition
- codehilite:
    guess_lang: false
    linenums: false
- footnotes
- toc:
    permalink: true
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.inlinehilite
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences
- pymdownx.tasklist:
    custom_checkbox: true

extra_css:
  - 'stylesheets/critic.css'

nav:
- index.md
- Solution:
  - solution.md
  - parameter-store.md
- For Developers:
  - setup.md
  - usage.md

extra:
  social:
    - type: 'github'
      link: 'https://github.com/dfds'
